name: Move Labeled Issues

on:
  issues:
    types: [labeled]

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  PROJECT_URL: ${{ secrets.PROJECT_URL }}

jobs:
  move_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue to Project Column
        uses: m7kvqbe1/github-action-move-issues@main
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          project-url: ${{ env.PROJECT_URL }}
          target-labels: "Size: Small, Size: Medium"
          target-column: "Todo"
          ignored-columns: "In Progress, Done"
          default-column: "Candidates"
